### PR TITLE
HIS-15: Add Senaite as the lab system

### PR DESCRIPTION
**Pull request by ssmusoke**

### CODE REVIEW

**Review by rbuisson — APPROVED** [review]

**Comment by rbuisson** [comment]
@corneliouzbett and @enyachoke, would you know anything about this?

**Comment by corneliouzbett** [comment]
Two things I think of:

1. The `configs/openmrs/frontend_config/config.json` config not being copied over to the correct directory. You can confirm this by checking the packaged distribution.
2. `SPA_CONFIG_URLS` points to `/openmrs/spa/ozone/ozone-frontend-config.json`. I think, in addition, you need to add the new config file so that you have: 
```env 
SPA_CONFIG_URLS=/openmrs/spa/ozone/ozone-frontend-config.json,/openmrs/spa/ozone/config.json
```
Check out this https://github.com/palladiumkenya/kenyahmis/blob/main/pom.xml#L304-L323

**Comment by corneliouzbett** [comment]
> @corneliouzbett If I am using the default configuration locations from ozone, I should not have to do this

Not sure how merging/overriding of frontend works here. However removing `config.json` should default to ozone config defaults.

This also depends on what components you've enabled; default Ozone config has more external links configured, such as the Superset link, which I think is not enabled in this distribution.

**Comment by ssmusoke** [comment]
@corneliouzbett the expectation is that the parent ozone distribution should be able to process overrides in the child project folders not just the parent one - this way the child distributions do not have to reinvent the wheel in a brittle manner - unless they decide to change the configuration locations

**Comment by rbuisson** [comment]
This displays correctly when trying your PR. See:
Screenshot 2024-09-06 at 12 12 54

**Review by rbuisson — APPROVED** [review]

**Pull request merged**
